# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.TextField(default=''),
        ),
    ]
