# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_auto_20170730_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='etymology',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
