# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_auto_20170810_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
