# Generated by Django 2.0.3 on 2018-03-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0008_viewer_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
