# Generated by Django 2.0.3 on 2018-03-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0009_auto_20180312_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
