# Generated by Django 2.0.3 on 2018-03-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0010_remove_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_default',
            field=models.NullBooleanField(),
        ),
    ]
