# Generated by Django 2.0.3 on 2018-03-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0011_child_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='is_default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
